### ISSUE TITLE
Minor suggestions for "Get started with JBoss EAP 7 using a Helm Chart" quick start

### ISSUE THREAD

**Issue by sangeetaraghu** [jboss-eap-up-and-running/openshift-console-quickstarts#4]
Hi @jmesnil,
 
Minor suggestions for "Get started with JBoss EAP 7 using a Helm Chart" quick start:

- Replace all occurrences of quickstart with quick start

- **Get started with JBoss EAP 7 using a Helm Chart**
  - In the overview page, do we want to give link to Customer portal or Redhat.com:
     [Red Hat® JBoss® Enterprise Application Platform (EAP)](https://www.redhat.com/en/technologies/jboss-middleware/application-platform)

 - In this quick start, you will complete **6** tasks:
    In this quick start, you will complete the **following** tasks:

- **Task - Create a JBoss EAP7 application with Helm**
   - 4. In the Helm Charts catalog, search for JBoss EAP 7.4. 
   - Add step 5:
   5. Click the Eap74 Helm chart card.
   The side panel displays information about the JBoss EAP 7 Helm chart
   -   In existing step 5 full stop missing:
      Click Install Helm Chart**.**
   - The details about the [Jakarta EE application](https://github.com/jboss-eap-up-and-running/eap7-getting-started) that you are building and deploying **are** specified in the build.uri field:
   - Add full stops at the end:
    - When the build is complete, a checkmark and the following message is displayed: Build #1 was complete**.**
    - When the second build is complete, a checkmark and the following message are displayed: Build #2 was complete **.**
   
- **Task View the associated code 3 of 6**
 - In the Topology view, the eap74 deployment displays a code icon in the bottom right-hand corner. **This icon either represents a Git repository that contains the associated code, or if the appropriate operators are installed, it represents the IDEs installed in your system.**
      @jmesnil Does this read correct?^

 - Click the icon to view the code associated with the application. 
     -  If the icon represents CodeReady Workspaces or Eclipse Che, clicking the icon opens the associated code in your IDE. 
     - If the icon represents a Git repository, clicking the icon opens the associated Git repository.

- **Task - View the build status** - (Change Build to build)
 - The two builds ~for~ eap74-build-artifacts and eap74 may take a few minutes to complete. 
 
 - **Task - View the pod status** - (Change Pod to pod)
  - 3. In the **Details** tab, -> Make "Details" bold
  - Note: In the Topology view, the dark outer circle ~D eap74 deployment~ indicates the pod status. -> Remove "D eap74 deployment"

**Comment by jmesnil** [comment]
> In the overview page, do we want to give link to Customer portal or Redhat.com:
[Red Hat® JBoss® Enterprise Application Platform (EAP)](https://www.redhat.com/en/technologies/jboss-middleware/application-platform)

When we discussed, it agreed the intro would link to redhat.com and the conclusion would link to customer portal. Do you want to revisit that decision?

>> In the Topology view, the eap74 deployment displays a code icon in the bottom right-hand corner. This icon either represents a Git repository that contains the associated code, or if the appropriate operators are installed, it represents the IDEs installed in your system.

Yes, this is correct. The behaviour depends on the operators that are installed in the openshift cluster.



However that these 2 points, I've addressed all your other suggestions in #5.
